version: "3.8"

services:
  api_a:
    build: .
    command: uvicorn api_Consome.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - api_b

  api_b:
    build: .
    command: uvicorn api_Moeda.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: cotacoes
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data:
